name: Workflow Events
on: [workflow_dispatch,push,commit] 
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Display Trigger Event
        run: echo "I've been triggered by ${{ github.event_name }} event"
